name: example-cron-action
'on':
  schedule:
    - cron: '*/5 * * * *'
jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - name: Do some heavy work
        run: echo $GITHUB_SHA
      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.WORKFLOWS_TOKEN }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: a1b1476caab93571a3fd977a9d0868d984c37b5a
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: .github/workflows/example-a1b1476caab93571a3fd977a9d0868d984c37b5a.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
      PR_NUMBER: '7'
