name: GitHub Actions Demo
on:
  pull_request:
    branches: 
      - main
    types: [closed]
jobs:
  Explore-GitHub-Actions:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job will trigger another action in 5 minutes."
      - run: echo "I hope"
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: cardinalby/schedule-job-action@v1
        with:
          ghToken: ${{ secrets.WORKFLOWS_TOKEN }}
          templateYmlFile: '.github-scheduled-workflows/example.yml'